# General
alias zshconfig="mate ~/.zshrc"
alias ohmyzsh="mate ~/.oh-my-zsh"

alias python="python3"
alias pip="pip3"
alias mkvenv="python3 -m venv venv"
alias mkvenv.="python3 -m venv .venv"
alias activate="source venv/bin/activate"
alias activate.="source .venv/bin/activate"

alias ..="cd .."
alias ...="cd ../.."
alias ll="ls -lah"
alias la="ls -A"
alias l="ls -CF"
alias c="clear"
alias mkdirp="mkdir -p"

alias zshrc="nano ~/.zshrc"
alias reload="source ~/.zshrc"

# Git
alias g="git"
alias gs="git status"
alias ga="git add"
alias gaa="git add ."
alias gc="git commit -m"
alias gca="git commit --amend"
alias gp="git push"
alias gpl="git pull"
alias gl="git log --oneline --graph --decorate"
alias gb="git branch"
alias gco="git checkout"
alias gcb="git checkout -b"
alias gd="git diff"
alias gds="git diff --staged"
alias gr="git restore"
alias grs="git restore --staged"